<?php

declare(strict_types=1);

use Infrangible\CatalogProductQtySteps\Block\Product\View\QtySteps;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var QtySteps $block */
?>

<?php if ($block->hasQtySteps()): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "productQtySteps": {
                    "productId": <?= /* @noEscape */ $block->getProduct()->getId(); ?>,
                    "steps": <?= /* @noEscape */ $block->getQtySteps(); ?>
                }
            }
        }
    </script>
<?php endif; ?>
