<?php

declare(strict_types=1);

use Infrangible\CatalogProductQtySteps\Block\Cart\QtySteps;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var QtySteps $block */
?>

<script type="text/x-magento-init">
    {
        "[data-block=minicart]": {
            "productQtyStepsMinicart": {
                "steps": <?= /* @noEscape */ $block->getQuoteQtySteps(); ?>
            }
        }
    }
</script>
